Redis
Hivemapper/hivemapper-data-logger pull request #25
Opened 2024-09-27 00:22 UTC by mazar-farran

2024-10-07 23:10 UTC, punov requested changes

2024-10-07 23:10 UTC, punov commented on logger/redis.go
> +		Ttff:             gnssdata.Ttff,
Correct me if I'm wrong, but I think the best for @derekhive would be to receive the raw data, and as raw as possible. This way we pass him formatted and aggregated data.
@mazar-farran if you will take a look at `HandleUbxMessage` method of gnss, I think passing full and every msg is what will be better here:
https://github.com/Hivemapper/hivemapper-data-logger/blob/add-snr/gnss-controller/device/neom9n/datafeed.go#L226

2024-10-08 18:48 UTC, punov approved these changes

2024-10-08 18:50 UTC, mazar-farran commented
Ticket: https://linear.app/hivemapper/issue/EDGE-278/datalogger-migrate-to-redis

Enabled with flag `--enable-redis-logs`

2024-10-08 18:51 UTC, merged